"""Initial schema

Revision ID: 0b269ec4d9df
Revises:
Create Date: 2026-09-25 00:27:05.917903

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b269ec4d9df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("reporter_contact", sa.String(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "water",
                "electricity",
                "sanitation",
                "roads",
                "streetlights",
                "other",
                name="categoryenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("high", "normal", "low", name="priorityenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "in_progress", "resolved", "rejected", name="statusenum"),
            nullable=False,
        ),
        sa.Column("ai_summary", sa.String(length=140), nullable=True),
        sa.Column("triaged_by", sa.String(), nullable=True),
        sa.Column("triage_latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_complaints_created_at", "complaints", ["created_at"], unique=False
    )
    op.create_index(
        "ix_complaints_status_priority",
        "complaints",
        ["status", "priority"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_complaints_status_priority", table_name="complaints")
    op.drop_index("ix_complaints_created_at", table_name="complaints")
    op.drop_table("complaints")
    # ### end Alembic commands ###
